### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by holographix** [adnan-wahab/pathgl#17]
because I find myself in the middle of a project and I'd need to take drastic technological decisions,
and since this seemed like a promising solution that matched my the da-facto situation, I was wondering if this repo was still under active development or not before jumping right on this boat. 

thx!
Aaron.

**Comment by alexanderGugel** [comment]
I don't think so.

**Comment by PhilAndrew** [comment]
Its dead!

**Comment by danpaulsmith** [comment]
We want answers Adnan!

**Comment by ming-codes** [comment]
Maybe we should start a fork?

**Comment by ming-codes** [comment]
There are recent commits, but author is not really responding on github issues.

**Comment by gdi2290** [comment]
nah it's dead. 
cc @adnan-wahab
